title: Georges Balogog # your name (or website title) here
logo: "/images/logofin.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionate about data technologies and Addressing optimization problems
  <br><br>
  Keen on learning 
  <br><br>
  <a href="https://www.linkedin.com/in/balogog-mandack-georges-lemuel-6810b9118 ">My LinkedIn Profile</a> 
  
# theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
